create table
  public.power_log (
    id bigint generated by default as identity not null,
    timestamp timestamp with time zone not null,
    power_state character varying not null,
    constraint power_log_pkey primary key (id)
  ) tablespace pg_default;